// Traducciones sencillas de la interfaz publica. No traduce productos de MySQL,
// porque la carta pertenece a la base de datos del restaurante.
const traducciones = {
  es: {
    inicio: 'Inicio',
    quienesSomos: 'Quienes somos',
    carta: 'Carta',
    hazPedido: 'Haz tu pedido',
    reserva: 'Reserva',
    horarios: 'Horarios',
    reservarMesa: 'Reservar mesa',
    hacerPedido: 'Hacer pedido',
    irReservas: 'Ir a reservas',
    irPedidos: 'Ir a pedidos',
    heroSuperior: 'Sushi tradicional con alma moderna',
    heroLead: 'La revolucion del sushi tradicional en Shushiara.',
    quienesSub: 'Quienes somos',
    quienesTitulo: 'Pescado fresco, tecnica japonesa y una experiencia directa.',
    quienesTexto1: 'Shushiara es un restaurante de sushi pensado para disfrutar en el local y tambien en casa. Preparamos arroz a diario, cortamos pescado fresco y trabajamos una carta clara: piezas tradicionales, rolls especiales, entrantes y combos para compartir.',
    quienesTexto2: 'Puedes reservar mesa para venir al local o realizar tu pedido a domicilio desde nuestra carta online.',
    valoracionMedia: 'valoracion media',
    minutosEntrega: 'minutos entrega',
    viernesSabado: 'viernes y sabado',
    mesaLocal: 'Mesa en local',
    reservaTitulo: 'Reservar mesa',
    reservaTexto: 'Elige fecha, hora, personas y zona. Ideal para cenas, comidas y celebraciones.',
    domicilio: 'A domicilio',
    pedidoTitulo: 'Realizar pedido',
    pedidoTexto: 'Abre la carta, anade productos al carrito y envia tu pedido directo a cocina.',
    abiertos: 'Abiertos todos los dias',
    horariosTexto: 'Servicio en local, reservas de mesa, recogida y pedidos a domicilio.',
    lunesJueves: 'Lunes a jueves',
    viernesSabadoDia: 'Viernes y sabado',
    domingo: 'Domingo',
    ubicacion: 'Ubicacion',
    ubicacionTitulo: 'Estamos en Valencia',
    ubicacionTexto: 'Encuentra Shushiara en Carrer de la Mar 24, 46003 Valencia. Puedes venir al local, recoger tu pedido o reservar mesa.',
    abrirMapa: 'Abrir en Maps',
    opiniones: 'Opiniones',
    opinionesTitulo: 'Lo que dicen de Shushiara',
    valoracionClientes: 'Valoracion media de nuestros clientes',
    footerDescripcion1: 'Restaurante japones con sushi fresco.',
    footerDescripcion2: 'Reservas en local y pedidos a domicilio.',
    menu: 'Menu',
    servicios: 'Servicios',
    pedidoDomicilio: 'Pedido a domicilio',
    recogidaLocal: 'Recogida en local',
    accesoInterno: 'Acceso interno',
    contacto: 'Contacto',
    copyright: '© 2026 Shushiara. Proyecto de pedidos y reservas.',
    lema: 'Sushi tradicional con alma moderna.',
    direccionLocal: 'Direccion',
    horario: 'Horario',
    mesaInfo1: 'Mesas para comidas, cenas y celebraciones.',
    mesaInfo2: 'Barra sushi para ver la preparacion en directo.',
    mesaInfo3: 'Terraza disponible segun clima y aforo.',
    mesaInfo4: 'Confirmacion telefonica de la reserva.',
    cartaOnline: 'Carta online',
    pedidoDomicilioTitulo: 'Pedido a domicilio',
    pedidoIntro: 'Elige sushi, ramen, sopas, noodles, postres y bebidas. Cocina japonesa preparada al momento.',
    entrega: 'Entrega',
    minimo: 'Minimo',
    valoracion: 'Valoracion',
    categorias: 'Categorias',
    todo: 'Todo',
    menuCompleto: 'Menu completo',
    nuestraCarta: 'Nuestra carta',
    buscar: 'Buscar sushi, combo, bebida...',
    tuCarrito: 'Tu carrito',
    pedido: 'Pedido',
    carritoVacio: 'El carrito esta vacio.',
    subtotal: 'Subtotal',
    envio: 'Envio',
    total: 'Total',
    datosEntrega: 'Datos de entrega',
    finalizar: 'Finalizar',
    nombre: 'Nombre',
    telefono: 'Telefono',
    direccion: 'Direccion',
    fecha: 'Fecha',
    hora: 'Hora',
    seleccionaHora: 'Selecciona hora',
    pago: 'Pago',
    tarjeta: 'Tarjeta',
    efectivo: 'Efectivo',
    pagoSimulado: 'Pago simulado',
    noCargo: 'No se realiza ningun cargo real.',
    titular: 'Titular',
    numeroTarjeta: 'Numero de tarjeta',
    caducidad: 'Caducidad',
    telefonoBizum: 'Telefono Bizum',
    pagoEfectivo: 'Pago en efectivo',
    efectivoInfo: 'El pedido se paga al repartidor o en el local al recogerlo.',
    notas: 'Notas',
    enviarPedido: 'Enviar pedido',
    reservaOnline: 'Reserva online',
    mesaShushiara: 'Mesa en Shushiara',
    reservaIntro: 'Ven a disfrutar sushi fresco en sala, terraza o barra. Reserva tu mesa en segundos.',
    ambiente: 'Ambiente',
    localJapones: 'Local japones',
    zona: 'Zona',
    salaTerraza: 'Sala y terraza',
    tuMesa: 'Tu mesa',
    experiencia: 'Una experiencia tranquila para comer sushi bien.',
    datosReserva: 'Datos de reserva',
    email: 'Email',
    personas: 'Personas',
    ocasion: 'Ocasion',
    reservaSinPago: 'Reserva sin pago previo',
    reservaSinPagoInfo: 'Solo guardamos tus datos para confirmar la mesa. No se cobra nada al reservar.',
    enviarReserva: 'Enviar reserva',
    reservaPreparada: 'Reserva preparada',
    antesVenirTitulo: 'Todo listo antes de sentarte.',
    antesVenirTexto: 'Al enviar la reserva guardamos tus datos y el equipo revisa disponibilidad real de sala, barra o terraza. Si hace falta ajustar algo, te llamamos antes del servicio.',
    consejoReserva1Titulo: 'Confirmacion telefonica',
    consejoReserva1Texto: 'La reserva queda registrada y se confirma por telefono si el local necesita revisar aforo.',
    consejoReserva2Titulo: 'Sin pago previo',
    consejoReserva2Texto: 'No se cobra nada al reservar mesa. El pago solo se realiza en el restaurante.',
    consejoReserva3Titulo: 'Alergias y preferencias',
    consejoReserva3Texto: 'Puedes indicar alergias, trona, celebraciones o una mesa tranquila en el campo de notas.',
  },
  en: {
    inicio: 'Home',
    quienesSomos: 'About us',
    carta: 'Menu',
    hazPedido: 'Order now',
    reserva: 'Book',
    horarios: 'Hours',
    reservarMesa: 'Book a table',
    hacerPedido: 'Order now',
    irReservas: 'Go to booking',
    irPedidos: 'Go to orders',
    heroSuperior: 'Traditional sushi with a modern soul',
    heroLead: 'The revolution of traditional sushi at Shushiara.',
    quienesSub: 'About us',
    quienesTitulo: 'Fresh fish, Japanese technique and a direct experience.',
    quienesTexto1: 'Shushiara is a sushi restaurant designed to enjoy both in the dining room and at home. We prepare rice daily, cut fresh fish and offer a clear menu: traditional pieces, special rolls, starters and sharing combos.',
    quienesTexto2: 'You can book a table at the restaurant or place your delivery order from our online menu.',
    valoracionMedia: 'average rating',
    minutosEntrega: 'delivery minutes',
    viernesSabado: 'Friday and Saturday',
    mesaLocal: 'Table at the restaurant',
    reservaTitulo: 'Book a table',
    reservaTexto: 'Choose date, time, guests and area. Perfect for lunches, dinners and celebrations.',
    domicilio: 'Delivery',
    pedidoTitulo: 'Place an order',
    pedidoTexto: 'Open the menu, add products to the cart and send your order straight to the kitchen.',
    abiertos: 'Open every day',
    horariosTexto: 'Dining room, table bookings, pickup and delivery orders.',
    lunesJueves: 'Monday to Thursday',
    viernesSabadoDia: 'Friday and Saturday',
    domingo: 'Sunday',
    ubicacion: 'Location',
    ubicacionTitulo: 'We are in Valencia',
    ubicacionTexto: 'Find Shushiara at Carrer de la Mar 24, 46003 Valencia. You can visit us, pick up your order or book a table.',
    abrirMapa: 'Abrir en Maps',
    opiniones: 'Reviews',
    opinionesTitulo: 'What people say about Shushiara',
    valoracionClientes: 'Average customer rating',
    footerDescripcion1: 'Japanese restaurant with fresh sushi.',
    footerDescripcion2: 'Table bookings and delivery orders.',
    menu: 'Menu',
    servicios: 'Services',
    pedidoDomicilio: 'Delivery order',
    recogidaLocal: 'Pickup',
    accesoInterno: 'Internal access',
    contacto: 'Contact',
    copyright: '© 2026 Shushiara. Orders and bookings project.',
    lema: 'Traditional sushi with a modern soul.',
    direccionLocal: 'Address',
    horario: 'Opening hours',
    mesaInfo1: 'Tables for lunches, dinners and celebrations.',
    mesaInfo2: 'Sushi bar to watch the preparation live.',
    mesaInfo3: 'Terrace available depending on weather and capacity.',
    mesaInfo4: 'Phone confirmation for the booking.',
    cartaOnline: 'Online menu',
    pedidoDomicilioTitulo: 'Delivery order',
    pedidoIntro: 'Choose sushi, ramen, soups, noodles, desserts and drinks. Japanese food prepared fresh.',
    entrega: 'Delivery',
    minimo: 'Minimum',
    valoracion: 'Rating',
    categorias: 'Categories',
    todo: 'All',
    menuCompleto: 'Full menu',
    nuestraCarta: 'Our menu',
    buscar: 'Search sushi, combo, drink...',
    tuCarrito: 'Your cart',
    pedido: 'Order',
    carritoVacio: 'Your cart is empty.',
    subtotal: 'Subtotal',
    envio: 'Delivery',
    total: 'Total',
    datosEntrega: 'Delivery details',
    finalizar: 'Checkout',
    nombre: 'Name',
    telefono: 'Phone',
    direccion: 'Address',
    fecha: 'Date',
    hora: 'Time',
    seleccionaHora: 'Select time',
    pago: 'Payment',
    tarjeta: 'Card',
    efectivo: 'Cash',
    pagoSimulado: 'Simulated payment',
    noCargo: 'No real charge is made.',
    titular: 'Cardholder',
    numeroTarjeta: 'Card number',
    caducidad: 'Expiry',
    telefonoBizum: 'Bizum phone',
    pagoEfectivo: 'Cash payment',
    efectivoInfo: 'The order is paid to the courier or at the restaurant when picking it up.',
    notas: 'Notes',
    enviarPedido: 'Send order',
    reservaOnline: 'Online booking',
    mesaShushiara: 'Table at Shushiara',
    reservaIntro: 'Enjoy fresh sushi in the dining room, terrace or sushi bar. Book your table in seconds.',
    ambiente: 'Atmosphere',
    localJapones: 'Japanese restaurant',
    zona: 'Area',
    salaTerraza: 'Dining room and terrace',
    tuMesa: 'Your table',
    experiencia: 'A calm experience to enjoy good sushi.',
    datosReserva: 'Booking details',
    email: 'Email',
    personas: 'Guests',
    ocasion: 'Occasion',
    reservaSinPago: 'Booking without prepayment',
    reservaSinPagoInfo: 'We only save your details to confirm the table. Nothing is charged when booking.',
    enviarReserva: 'Send booking',
    reservaPreparada: 'Prepared booking',
    antesVenirTitulo: 'Everything ready before you sit down.',
    antesVenirTexto: 'When you send the booking, we save your details and the team checks real availability in the dining room, sushi bar or terrace. If anything needs adjusting, we call you before service.',
    consejoReserva1Titulo: 'Phone confirmation',
    consejoReserva1Texto: 'The booking is registered and confirmed by phone if the restaurant needs to check capacity.',
    consejoReserva2Titulo: 'No prepayment',
    consejoReserva2Texto: 'Nothing is charged when booking a table. Payment is only made at the restaurant.',
    consejoReserva3Titulo: 'Allergies and preferences',
    consejoReserva3Texto: 'You can add allergies, a high chair, celebrations or a quiet table in the notes field.',
  },
};

function aplicarIdioma(idioma) {
  const diccionario = traducciones[idioma] || traducciones.es;
  document.documentElement.lang = idioma;
  localStorage.setItem('shushiara_idioma', idioma);

  document.querySelectorAll('[data-i18n]').forEach((elemento) => {
    const clave = elemento.dataset.i18n;
    if (diccionario[clave]) {
      elemento.textContent = diccionario[clave];
    }
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach((elemento) => {
    const clave = elemento.dataset.i18nPlaceholder;
    if (diccionario[clave]) {
      elemento.placeholder = diccionario[clave];
    }
  });

  document.querySelectorAll('[data-language]').forEach((boton) => {
    boton.classList.toggle('active', boton.dataset.language === idioma);
  });
}

document.querySelectorAll('[data-language]').forEach((boton) => {
  boton.addEventListener('click', () => aplicarIdioma(boton.dataset.language));
});

aplicarIdioma(localStorage.getItem('shushiara_idioma') || 'es');
